spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/tour?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true